info:
  contact: {}
  license: {}
paths:
  /api/v1/rooms:
    delete:
      parameters:
      - description: RoomId
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 删除聊天室
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取聊天室
    post:
      parameters:
      - description: RoomType
        in: query
        name: room_type
        required: true
        type: integer
      - description: PeopleLimit
        in: query
        name: people_limit
        required: true
        type: integer
      - description: RoomCount
        in: query
        name: room_count
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 新增聊天室
    put:
      parameters:
      - description: RoomId
        in: query
        name: id
        required: true
        type: string
      - description: RoomName
        in: query
        name: room_name
        type: string
      - description: RoomDesc
        in: query
        name: room_desc
        type: string
      - description: RoomType
        in: query
        name: room_type
        type: integer
      - description: PeopleLimit
        in: query
        name: people_limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 修改聊天室
swagger: "2.0"
