info:
  contact: {}
  license: {}
paths:
  /api/v1/post_types:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取 PostType 列表
      tags:
      - Post Type
    post:
      parameters:
      - description: Type Name
        in: query
        name: type_name
        required: true
        type: string
      - description: Type Structure
        in: query
        name: type_structure
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 新增 PostType
      tags:
      - Post Type
  /api/v1/post_types/{id}:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 删除 PostType
      tags:
      - Post Type
  /api/v1/room_members:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取room member list
      tags:
      - Room Member
  /api/v1/room_prototypes:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取聊天室原型列表
      tags:
      - Room Prototype
    post:
      parameters:
      - description: PrototypeName
        in: query
        name: prototype_name
        required: true
        type: string
      - description: PeopleLimit
        in: query
        name: people_limit
        required: true
        type: integer
      - description: Friendship
        in: query
        name: friendship
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 新增聊天室原型
      tags:
      - Room Prototype
  /api/v1/room_prototypes/{id}:
    delete:
      parameters:
      - description: Room Prototype Id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 删除聊天室原型
      tags:
      - Room Prototype
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 根据ID获取聊天室原型
      tags:
      - Room Prototype
  /api/v1/rooms:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取聊天室列表
      tags:
      - Room
    post:
      parameters:
      - description: RoomType
        in: query
        name: room_type
        required: true
        type: integer
      - description: PeopleLimit
        in: query
        name: people_limit
        required: true
        type: integer
      - description: RoomCount
        in: query
        name: room_count
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 新增聊天室
      tags:
      - Room
  /api/v1/rooms/{id}:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 删除聊天室
      tags:
      - Room
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取指定聊天室
      tags:
      - Room
    put:
      parameters:
      - description: RoomName
        in: query
        name: room_name
        type: string
      - description: RoomDesc
        in: query
        name: room_desc
        type: string
      - description: RoomType
        in: query
        name: room_type
        type: integer
      - description: PeopleLimit
        in: query
        name: people_limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 修改聊天室
      tags:
      - Room
  /api/v1/users:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取user列表
      tags:
      - User
  /api/v1/users/{id}:
    delete:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 删除user
      tags:
      - User
    get:
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取指定user
      tags:
      - User
    put:
      parameters:
      - description: Username
        in: query
        name: username
        required: true
        type: integer
      - description: Nickname
        in: query
        name: nickname
        required: true
        type: integer
      - description: password
        in: query
        name: password
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 修改user
      tags:
      - User
  /auth:
    post:
      parameters:
      - description: Username
        in: query
        name: username
        required: true
        type: string
      - description: Password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":2000,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 登录
      tags:
      - User
  /register:
    post:
      parameters:
      - description: Username
        in: query
        name: username
        required: true
        type: string
      - description: Nickname
        in: query
        name: nickname
        required: true
        type: string
      - description: Password
        in: query
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":2000,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 注册
      tags:
      - User
swagger: "2.0"
